export const data = {
    list: [
        {
            entity: {
                id: 6,
                parentMenuId: 0,
                name: "baseManage",
                icon: "el-icon-news",
                alias: "基本要素",
                state: "ENABLE",
                sort: 1,
                value: null,
                type: "NONE",
                discription: "用于用户管理的菜单",
                createUserId: 1,
            },
            childs: [
                {
                    entity: {
                        id: 7,
                        parentMenuId: 6,
                        name: "/baseManage/marker",
                        icon: "el-icon-user\r\n",
                        alias: "点要素",
                        state: "ENABLE",
                        sort: 0,
                        value: "/baseManage/marker",
                        type: "NONE",
                        discription: "基本图层点信息",
                        createUserId: 1,
                    },
                },
                {
                    entity: {
                        id: 7,
                        parentMenuId: 6,
                        name: "/baseManage/line",
                        icon: "el-icon-user\r\n",
                        alias: "线要素",
                        state: "ENABLE",
                        sort: 0,
                        value: "/baseManage/line",
                        type: "NONE",
                        discription: "基本图层点信息",
                        createUserId: 1,
                    },
                },
            ],
        },
        {
            entity: {
                id: 9,
                parentMenuId: 0,
                name: "roleManage",
                icon: "el-icon-rank",
                alias: "权限管理",
                state: "ENABLE",
                sort: 2,
                value: null,
                type: "NONE",
                discription: "用于内容管理的菜单",
                createUserId: 1,
            },
            childs: [
                {
                    entity: {
                        id: 10,
                        parentMenuId: 9,
                        name: "/roleManage/roleList",
                        icon: "el-icon-s-tools\n\r\n",
                        alias: "角色中心",
                        state: "ENABLE",
                        sort: 0,
                        value: "/roleManage/roleList",
                        type: "NONE",
                        discription: "角色中心",
                        createUserId: 1,
                    },
                },
                {
                    entity: {
                        id: 8985,
                        parentMenuId: 9,
                        name: "/roleManage/giveAuth",
                        icon: "el-icon-s-order\n\r\n",
                        alias: "角色授权",
                        state: "ENABLE",
                        sort: 0,
                        value: "/roleManage/giveAuth",
                        type: "NONE",
                        discription: "角色授权",
                        createUserId: 1,
                    },
                },
                {
                    entity: {
                        id: 11,
                        parentMenuId: 9,
                        name: "/roleManage/authList",
                        icon: "el-icon-help\r\n",
                        alias: "菜单资源",
                        state: "ENABLE",
                        sort: 0,
                        value: "/roleManage/authList",
                        type: "NONE",
                        discription: "资源中心",
                        createUserId: 1,
                    },
                },
                {
                    entity: {
                        id: 118,
                        parentMenuId: 9,
                        name: "/roleManage/apiList",
                        icon: "el-icon-s-cooperation\n\r\n",
                        alias: "接口资源",
                        state: "ENABLE",
                        sort: 0,
                        value: "/roleManage/apiList",
                        type: "NONE",
                        discription: "资源中心",
                        createUserId: 1,
                    },
                },
            ],
        },
        {
            entity: {
                id: 12,
                parentMenuId: 0,
                name: "organManage",
                icon: "el-icon-news",
                alias: "组织管理",
                state: "ENABLE",
                sort: 1,
                value: null,
                type: "NONE",
                discription: "用于用户管理的菜单",
                createUserId: 1,
            },
            childs: [
                {
                    entity: {
                        id: 128922,
                        parentMenuId: 12,
                        name: "/organManage/organList",
                        icon: "el-icon-s-flag\r\n",
                        alias: "组织中心",
                        state: "ENABLE",
                        sort: 0,
                        value: "/organManage/organList",
                        type: "NONE",
                        discription: "用于帐号管理的菜单",
                        createUserId: 1,
                    },
                },
            ],
        },
        {
            entity: {
                id: 1289,
                parentMenuId: 0,
                name: "systemManage",
                icon: "el-icon-news",
                alias: "系统管理",
                state: "ENABLE",
                sort: 1,
                value: null,
                type: "NONE",
                discription: "用于用户管理的菜单",
                createUserId: 1,
            },
            childs: [
                {
                    entity: {
                        id: 12887,
                        parentMenuId: 1289,
                        name: "/systemManage/systemList",
                        icon: "el-icon-phone-outline\r\n",
                        alias: "系统中心",
                        state: "ENABLE",
                        sort: 0,
                        value: "/systemManage/systemList",
                        type: "NONE",
                        discription: "用于帐号管理的菜单",
                        createUserId: 1,
                    },
                },
            ],
        },
    ],
};
